revert bitbucket docs
apache/incubator-devlake-website pull request #417
Opened 2023-02-01 12:09 UTC by mindlesscloud

# Summary
Since the bitbucket plugin is not fully compatible with the blueprintV200, It is better to create blueprints in the same way as v0.14.0, which could utilize the `gitextractor` to collect git data

2023-02-01 21:56 UTC, hezyin commented on docs/Plugins/bitbucket.md
>  - Configuring Bitbucket via Config UI's [advanced mode](/UserManuals/ConfigUI/AdvancedMode.md#9-BitBucket).
@mindlesscloud Let's not suggest users configure Bitbucket via advanced mode.

2023-02-01 21:57 UTC, hezyin commented on versioned_docs/version-v0.15/Plugins/bitbucket.md
>  - Configuring Bitbucket via Config UI's [advanced mode](/UserManuals/ConfigUI/AdvancedMode.md#9-BitBucket).
@mindlesscloud Same here.

2023-02-01 21:57 UTC, hezyin requested changes
Please see my comments.

2023-02-07 09:15 UTC, Startrekzky approved these changes, later dismissed
Not sure if this is what we want, but let's merge it first.

2023-02-14 18:20 UTC, hezyin submitted a review, later dismissed
LGTM

2023-02-14 19:16 UTC, hezyin approved these changes
LGTM

2023-02-14 19:36 UTC, merged