Updated the [Install via docker compose command]
apache/incubator-devlake-website pull request #418
Opened 2023-02-02 17:55 UTC by lavakush07

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [✅ ] I have `npm run build` and `npm run serve` locally before submitting this PR
- [✅ ] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
https://github.com/apache/incubator-devlake/issues/4290

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

2023-02-03 02:16 UTC, abeizn commented
@lavakush07 Thanks for you pr, Docker Compose was introduced in this version (Docker Inc., v2.13.0), so i think docker-compose is right. Or in the doc, when the user use docker v2.13.0, them can use docker-compose.

2023-02-04 05:34 UTC, lavakush07 commented
Can I please get more clarity on this as it was mentioned in the website  :
![image](https://user-images.githubusercontent.com/70131581/216750672-df6db256-91da-4c75-b24f-3b6bf8b43154.png)

2023-02-06 02:41 UTC, abeizn commented
> Can I please get more clarity on this as it was mentioned in the website : ![image](https://user-images.githubusercontent.com/70131581/216750672-df6db256-91da-4c75-b24f-3b6bf8b43154.png)

Or you should add a sentence, if the version of docker desktop installed by the user is too low to use `docker compose up -d`, please use `docker-compose up -d`

2023-02-06 18:12 UTC, lavakush07 commented
> > Can I please get more clarity on this as it was mentioned in the website : ![image](https://user-images.githubusercontent.com/70131581/216750672-df6db256-91da-4c75-b24f-3b6bf8b43154.png)
> 
> Or you should add a sentence, if the version of docker desktop installed by the user is too low to use `docker compose up -d`, please use `docker-compose up -d`

Thank you @abeizn , Updated the PR with the required changes.

2023-02-07 02:48 UTC, Startrekzky requested changes, later dismissed

2023-02-07 02:48 UTC, Startrekzky commented on docs/GettingStarted/DockerComposeSetup.md
> +3. If [Docker v2.13.0+](https://docs.docker.com/get-docker) Run `docker compose up -d` to launch DevLake or else Run `docker-compose up -d`.
The wording needs polishing.

2023-02-27 03:29 UTC, abeizn approved these changes

2023-02-27 03:31 UTC, abeizn approved these changes

2023-02-27 03:37 UTC, abeizn commented on docs/GettingStarted/DockerComposeSetup.md
> +3. If [Docker v2.13.0+](https://docs.docker.com/get-docker) Run `docker compose up -d` to launch DevLake or else Run `docker-compose up -d`.
> The wording needs polishing.

merge first, I will update later.

2023-02-27 06:24 UTC, merged